services:
  dev:
    container_name: fastapi-devcontainer
    build:
      context: .
      dockerfile: app/Dockerfile
      target: development
    volumes:
      - ./:/workspace:cached
      - venv:/workspace/.venv
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true

volumes:
  venv:
